### ISSUE TITLE
Support uploading to remote host

### ISSUE THREAD

**Issue by MaffooClock** [MaffooClock/MrRadar#5]
Currently, this utility outputs files only to a local directory.

Should we consider adding a flag that allows the user to specify a URI to a remote FTP or SSH host?  Or might this be out of scope, and just leave it up to the user on what to do with the output?

**Comment by dkowis** [comment]
Personally, I would not do this. There are myriad tools out there to rsync stuff to locations.

**Comment by MaffooClock** [comment]
Agreed.  This utility should just do what it does without adding additional functionality that is already well-served by other tools.
